### ISSUE TITLE
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'

### ISSUE THREAD

**Issue by RaghavK16** [streamlit/demo-face-gan#18]
On cloning and running on my local machine, after following each step clearly, I get the following message:

```

Traceback (most recent call last):
  File "c:\users\raghav khullar\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\raghav khullar\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Raghav Khullar\AppData\Local\Programs\Python\Python37\Scripts\streamlit.exe\__main__.py", line 4, in <module>
  File "c:\users\raghav khullar\appdata\local\programs\python\python37\lib\site-packages\streamlit\__init__.py", line 75, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "c:\users\raghav khullar\appdata\local\programs\python\python37\lib\site-packages\streamlit\delta_generator.py", line 25, in <module>
    from streamlit.proto import Block_pb2
  File "c:\users\raghav khullar\appdata\local\programs\python\python37\lib\site-packages\streamlit\proto\Block_pb2.py", line 21, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
```

How can I resolve this?

**Comment by randyzwitch** [comment]
You need to update your protobuf library. For whatever reason, the Python dependency solver doesn't seem to get this right on all systems:

`pip install --upgrade protobuf`

Best,
Randy
