### ISSUE TITLE
After installing packages manually, it still does not run.

### ISSUE THREAD

**Issue by haellingsen** [streamlit/demo-face-gan#36]
Maybe more packages missing or 3.10 not supported.

Python version
```
(venv) 08:54:38|C|demo-face-gan> python --version
Python 3.10.0
```

My requirements.txt
[requirements.txt](https://github.com/streamlit/demo-face-gan/files/9306767/requirements.txt)

Error
```
2022-08-11 08:43:47.223040: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2022-08-11 08:43:47.223212: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
C:\Users\HaraldEllingsen\demo-face-gan\pg_gan\tfutil.py:179: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if v.shape.ndims is 0:
C:\Users\HaraldEllingsen\demo-face-gan\pg_gan\tfutil.py:181: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif v.shape.ndims is 1:
C:\Users\HaraldEllingsen\demo-face-gan\pg_gan\tfutil_cpu.py:179: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if v.shape.ndims is 0:
C:\Users\HaraldEllingsen\demo-face-gan\pg_gan\tfutil_cpu.py:181: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif v.shape.ndims is 1:
2022-08-11 08:44:55.899 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\HaraldEllingsen\demo-face-gan\venv\lib\site-packages\streamlit\caching\cache_utils.py", line 126, in get_or_create_cached_value
    return_value = cache.read_value(value_key)
  File "C:\Users\HaraldEllingsen\demo-face-gan\venv\lib\site-packages\streamlit\caching\singleton_decorator.py", line 262, in read_value
    raise CacheKeyNotFoundError()
streamlit.caching.cache_errors.CacheKeyNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HaraldEllingsen\demo-face-gan\venv\lib\site-packages\streamlit\scriptrunner\script_runner.py", line 557, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\HaraldEllingsen\demo-face-gan\streamlit_app.py", line 227, in <module>
    main()
[requirements.txt](https://github.com/streamlit/demo-face-gan/files/9306758/requirements.txt)

  File "C:\Users\HaraldEllingsen\demo-face-gan\streamlit_app.py", line 28, in main
    session, pg_gan_model = load_pg_gan_model()
  File "C:\Users\HaraldEllingsen\demo-face-gan\venv\lib\site-packages\streamlit\caching\cache_utils.py", line 145, in wrapper
    return get_or_create_cached_value()
  File "C:\Users\HaraldEllingsen\demo-face-gan\venv\lib\site-packages\streamlit\caching\cache_utils.py", line 137, in get_or_create_cached_value
    return_value = func(*args, **kwargs)
  File "C:\Users\HaraldEllingsen\demo-face-gan\streamlit_app.py", line 137, in load_pg_gan_model
    config = tf.ConfigProto(allow_soft_placement=True)
AttributeError: module 'tensorflow' has no attribute 'ConfigProto'
2022-08-11 08:45:05.428 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\HaraldEllingsen\demo-face-gan\venv\lib\site-packages\streamlit\caching\cache_utils.py", line 126, in get_or_create_cached_value
    return_value = cache.read_value(value_key)
  File "C:\Users\HaraldEllingsen\demo-face-gan\venv\lib\site-packages\streamlit\caching\singleton_decorator.py", line 262, in read_value
    raise CacheKeyNotFoundError()
streamlit.caching.cache_errors.CacheKeyNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HaraldEllingsen\demo-face-gan\venv\lib\site-packages\streamlit\scriptrunner\script_runner.py", line 557, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\HaraldEllingsen\demo-face-gan\streamlit_app.py", line 227, in <module>
    main()
  File "C:\Users\HaraldEllingsen\demo-face-gan\streamlit_app.py", line 28, in main
    session, pg_gan_model = load_pg_gan_model()
  File "C:\Users\HaraldEllingsen\demo-face-gan\venv\lib\site-packages\streamlit\caching\cache_utils.py", line 145, in wrapper
    return get_or_create_cached_value()
  File "C:\Users\HaraldEllingsen\demo-face-gan\venv\lib\site-packages\streamlit\caching\cache_utils.py", line 137, in get_or_create_cached_value
    return_value = func(*args, **kwargs)
  File "C:\Users\HaraldEllingsen\demo-face-gan\streamlit_app.py", line 137, in load_pg_gan_model
    config = tf.ConfigProto(allow_soft_placement=True)
AttributeError: module 'tensorflow' has no attribute 'ConfigProto'

```

**Comment by arnaudmiribel** [comment]
Hey @haellingsen, 

Sorry for the late reply! Indeed this app does not work for Python 3.10 as can be seen in the README:

> The demo requires Python 3.6 or 3.7 (The version of TensorFlow we specify in requirements.txt is not supported in Python 3.8+)

Closing this
